{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimDate\",\"DimCity\",\"DimCustomer\",\"DimSalesperson\",\"DimProduct\",\"FactSale\",\"DimSalespersonTarget\",\"Color Formats\",\"Employee_csv\",\"DimCategory\",\"Dimension Stock Item\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1733.0 (24.12)+af51d793b3eacaf90fc70909aa713164bbd22a66"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Color Formats",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\snosek\\Documents\\studia\\BI\\Dodatkowe dane\\Color Formats.csv\"),[Delimiter=\";\", Columns=3, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Color\", type text}, {\"Background Color Format\", type text}, {\"Font Color Format\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "a904d173-429a-400e-b6bd-b1928382a9e1"
      }
    ],
    "relationships": [
      {
        "name": "c1645ac3-4deb-46ba-9fa3-67851bde4163",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Delivery Date",
        "fromTable": "FactSale",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "c65a7497-1b64-474a-a030-a65705067773",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Invoice Date",
        "fromTable": "FactSale",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "1d98a1c0-3a31-4450-84a7-b54990a96377",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "City Key",
        "fromTable": "FactSale",
        "toColumn": "City Key",
        "toTable": "DimCity"
      },
      {
        "name": "21c66573-17ab-4fc8-a294-74653eb9478b",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Customer Key",
        "fromTable": "FactSale",
        "toColumn": "Customer Key",
        "toTable": "DimCustomer"
      },
      {
        "name": "b2b30948-3c88-4e2c-9c0e-2d376db40c05",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Salesperson Key",
        "fromTable": "FactSale",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      },
      {
        "name": "e505766f-9996-c6b3-207e-1e4aa8d970cd",
        "fromColumn": "Stock Item Key",
        "fromTable": "FactSale",
        "toColumn": "Stock Item Key",
        "toTable": "DimProduct"
      },
      {
        "name": "e5466762-5826-8c94-9865-201edd571ef7",
        "fromColumn": "EmployeeID",
        "fromTable": "DimSalespersonTarget",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      },
      {
        "name": "47c7a16f-931b-5af2-53a2-fe9f35b60112",
        "fromColumn": "WWI Employee ID",
        "fromTable": "DimSalesperson",
        "isActive": false,
        "toColumn": "WWI Employee ID",
        "toTable": "Employee_csv"
      },
      {
        "name": "a2775fee-02a1-d0b3-230c-631fadef4a2c",
        "fromColumn": "WWI Stock Item ID",
        "fromTable": "DimProduct",
        "toColumn": "WWI Stock Item ID",
        "toTable": "DimCategory"
      },
      {
        "name": "50618bbb-1b39-2551-37a6-94fe17cd24dd",
        "fromColumn": "TargetMonth",
        "fromTable": "DimSalespersonTarget",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "afb084e7-d097-47ba-945d-a82b4597c031",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Stock Item Key",
        "fromTable": "FactSale",
        "toColumn": "Stock Item Key",
        "toTable": "Dimension Stock Item"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "949a7e0b-84f2-4eb1-8b7b-c5b594930220",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db298160-ae8d-4545-8ab6-74a4bdb50d92",
            "sourceColumn": "Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec87add2-00fd-4c33-94ba-6d79b173ead5",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "52ba0140-a8b3-41f8-8916-de843b3790de",
            "sortByColumn": "Calendar Month Number",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Short Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42fdd70f-b81a-4d5b-b737-8a69f1948164",
            "sourceColumn": "Short Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "38dc07cd-7692-4ef6-8ff3-492be492517e",
            "sourceColumn": "Calendar Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "310edf0d-241b-4deb-bf5c-ab24fe918129",
            "sourceColumn": "Calendar Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34d52efe-10c9-4310-84bf-3a19c99aee29",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4d3aaa5-b4f8-4b6c-9ff7-4d9d2657cfaf",
            "sourceColumn": "Calendar Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a6e54d88-10cf-488c-ab29-5981fcacf7af",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6045925e-1dbf-4281-a873-e45a7d43bba2",
            "sourceColumn": "Fiscal Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46df507e-a199-49cc-8e2b-33b6ba497490",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b14263e7-4bd8-4cd8-bd94-4ec840457a2c",
            "sourceColumn": "Fiscal Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "ISO Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e0de9629-30a2-4fcd-a286-24a02738cca3",
            "sourceColumn": "ISO Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(DimDate[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "911dcba2-66f5-4076-9d9a-dc911771d43c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "66ce537b-b8ef-4e85-a3c1-ba80208061f6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "(YEAR(DimDate[Date])*100)+MONTH(DimDate[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0a86b95f-de61-432f-b41b-28145989defc",
            "summarizeBy": "count",
            "type": "calculated"
          },
          {
            "name": "TargetMonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(DimDate[Date], \"M-yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "50c93f06-5de2-4ff8-b477-92a6d2745c2d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Calendar Year",
                "column": "Calendar Year",
                "lineageTag": "4e4f5067-2c8e-4c57-a3d9-fc48f81f9fab",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d3bb8b50-0d1f-46c9-982c-848de15efbf3",
                "ordinal": 1
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "23af64bc-d35b-46c0-bc83-fcd0926173d0",
                "ordinal": 2
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "36b91143-4060-439e-86b2-8f3180b52ad9",
                "ordinal": 3
              }
            ],
            "lineageTag": "038500af-4f7f-4f48-b253-22e6e34979b9"
          }
        ],
        "lineageTag": "153133ba-ca93-4fe6-ab39-a10987a89c43",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    Dimension_Date = Source{[Schema=\"Dimension\",Item=\"Date\"]}[Data]",
                "in",
                "    Dimension_Date"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9291067c-34ae-4da0-bd80-42e7317ae182",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI City ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2997820c-4030-4498-a586-02d94abee2c0",
            "sourceColumn": "WWI City ID",
            "summarizeBy": "count"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "displayFolder": "Regions",
            "lineageTag": "31b7e933-f43f-4c23-bbda-613b2ce77917",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "displayFolder": "Regions",
            "lineageTag": "94db5402-ecae-48e8-82d4-ad1f6e6eac1b",
            "sourceColumn": "State Province",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "displayFolder": "Regions",
            "lineageTag": "30761662-bfc1-47cd-b467-bf075d452de0",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89b0033f-cf66-453c-83cd-ddb9df26c4f6",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b9cb913-d5f6-429d-9cdc-20ffacaef55c",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "626f511c-733d-4f95-93f9-742f8ca85e71",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Subregion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "6837a720-5c8a-4d6e-9e46-2273298e145d",
            "sourceColumn": "Subregion",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39d0e797-7605-4740-958b-764064c65a8c",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Recorded Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e072c8c4-b665-43db-b0cf-396c55a808e3",
            "sourceColumn": "Latest Recorded Population",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "40b5977a-49a2-4c22-af2c-d140661c585d",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6b9b874b-b433-48dd-adeb-67eb4f4744ba",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7cd056e-192a-4a72-b793-ac5172d18bb3",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5c0440a-0320-4c22-9ee0-1f9aa9271994",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Regions",
            "levels": [
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "4c3659e9-24d7-4868-9133-04e92de0fc2e",
                "ordinal": 0
              },
              {
                "name": "State Province",
                "column": "State Province",
                "lineageTag": "42e7e208-cee4-41d2-b45e-f18d48d0ea82",
                "ordinal": 1
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "72d4c083-6abd-443e-82a3-bdf025f1f364",
                "ordinal": 2
              },
              {
                "name": "Subregion",
                "column": "Subregion",
                "lineageTag": "3b1c74e4-02b3-4101-b500-bd28afa7edf1",
                "ordinal": 3
              }
            ],
            "lineageTag": "d895a35e-d961-41e8-baf9-7fe0f0b41ee8"
          }
        ],
        "lineageTag": "d81eb89b-8aca-4ad5-a8db-9bce3c5be58d",
        "partitions": [
          {
            "name": "DimCity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    Dimension_City = Source{[Schema=\"Dimension\",Item=\"City\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(Dimension_City,1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Top Rows\",{\"Lineage Key\", \"Fact.Order\", \"Fact.Sale\"}),",
                "    #\"Wstawiony tekst między ogranicznikami\" = Table.AddColumn(#\"Removed Columns\", \"Longitude\", each Text.BetweenDelimiters([Location], \"(\", \" \"), type text),",
                "    #\"Wstawiony tekst między ogranicznikami1\" = Table.AddColumn(#\"Wstawiony tekst między ogranicznikami\", \"Latitude\", each Text.BetweenDelimiters([Location], \" \", \")\", 1, 0), type text)",
                "in",
                "    #\"Wstawiony tekst między ogranicznikami1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "067915df-f955-4f36-8371-c95df634ba85",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1f121e1-4ab0-4085-b1b9-628313777318",
            "sourceColumn": "WWI Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customers",
            "lineageTag": "028aa967-5634-426b-8718-4bb2c62a6545",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Bill To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef7a250c-51eb-43bd-befc-6de7cc55bcad",
            "sourceColumn": "Bill To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d530a6e-3b64-4c2d-8d35-09556542dc4f",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Customers",
            "lineageTag": "a03f7ceb-0dec-42b1-8f49-d3673fb706a6",
            "sourceColumn": "Buying Group",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d23d90b-9fc9-4d8b-81be-8d8c834fae33",
            "sourceColumn": "Primary Contact",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "2a2a1b90-fe3b-4eac-8ae5-3e38c2e1c531",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f2466128-4529-43c6-a43a-f0207bebe2a8",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5f5c9274-1087-4a83-8f01-ad946aa54296",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b1787142-94e3-4437-a99b-414b8ce1524f",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bf96f8e3-9873-4995-a84a-1d493f06103f",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    Dimension_Customer = Source{[Schema=\"Dimension\",Item=\"Customer\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(Dimension_Customer,1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Top Rows\",{\"Fact.Movement\", \"Fact.Sale(Customer Key)\", \"Fact.Order\", \"Fact.Sale(Customer Key) 2\", \"Fact.Transaction(Customer Key)\", \"Fact.Transaction(Customer Key) 2\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimSalesperson",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "EmployeeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fd6cfb45-3dd9-4d0b-8f7e-4a2ebd292dae",
            "sourceColumn": "EmployeeId",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "670d2212-3501-4fc5-9f2c-9c5ba9ca69e1",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Salesperson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "164926af-e9c3-447c-be8b-dab574f7f5cc",
            "sourceColumn": "Salesperson",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e9c26887-a4ca-4682-80f7-d1c57f91d427",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "782530b9-6265-47d7-9ca4-7374e77fa5b8",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36086020-1ba4-49b4-99a6-332dd1dcd10b",
            "sourceColumn": "First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c058924-6c03-4ce7-9279-c914b584656c",
            "sourceColumn": "Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6837250-dde9-46d5-b5c4-c5f4fc394a4a",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38a30c28-bfb4-43d2-b079-de62ee963a6f",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4083b068-f66d-4f9b-965f-cbba03874af6",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f73151d4-995f-4a6a-8d83-62d15aeaee2f",
        "partitions": [
          {
            "name": "DimSalesperson",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    Dimension_Employee = Source{[Schema=\"Dimension\",Item=\"Employee\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(Dimension_Employee, each ([Is Salesperson] = true)),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"Employee Key\", \"WWI Employee ID\", \"Employee\", \"Valid From\", \"Valid To\"}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Removed Other Columns\", \"Text Before Delimiter\", each Text.BeforeDelimiter([Employee], \" \"), type text),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(#\"Inserted Text Before Delimiter\", \"Text After Delimiter\", each Text.AfterDelimiter([Employee], \" \"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text After Delimiter\",{{\"Text Before Delimiter\", \"First Name\"}, {\"Text After Delimiter\", \"Last Name\"}, {\"Employee\", \"Salesperson\"}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"WWI Employee ID\"}, Employee_csv, {\"WWI Employee ID\"}, \"Employee_csv\", JoinKind.LeftOuter),",
                "    #\"Expanded Employee_csv\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Employee_csv\", {\"JobTitle\", \"BusinessUnit\", \"Age\"}, {\"Employee_csv.JobTitle\", \"Employee_csv.BusinessUnit\", \"Employee_csv.Age\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Employee_csv\",{{\"Employee_csv.JobTitle\", \"JobTitle\"}, {\"Employee_csv.BusinessUnit\", \"BusinessUnit\"}, {\"Employee_csv.Age\", \"Age\"}, {\"Employee Key\", \"EmployeeId\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0dcdcdcc-a7d3-4c02-88f0-1398f337ebb3",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "763569d9-22cb-4daa-b853-f44e63d98f7c",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0c7edda-066c-4c5d-8aa2-31f3c75a59e7",
            "sourceColumn": "Stock Item",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e643b0a-5baa-4cfc-93ce-eecd5c00655a",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7561af12-5bc1-4773-9e25-38d6f76054ec",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "271f2332-d190-4683-bd14-8605913c2088",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3161a5b-3b87-4232-9a4c-c957d88dca5c",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Background Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "4c4181d8-c7d7-4344-b61e-7552e882d2d8",
            "sourceColumn": "Background Color Format",
            "summarizeBy": "none"
          },
          {
            "name": "Font Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "155b92a2-c364-42a2-9a82-3275a0dc066d",
            "sourceColumn": "Font Color Format",
            "summarizeBy": "none"
          },
          {
            "name": "Selling Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE('Dimension Stock Item'[Selling Package], 'Dimension Stock Item'[WWI Stock Item ID], DimProduct[WWI Stock Item ID])",
            "isDataTypeInferred": true,
            "lineageTag": "7d3f5f70-33e5-4405-ab3f-6a331455db63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE('Dimension Stock Item'[Brand], 'Dimension Stock Item'[WWI Stock Item ID], DimProduct[WWI Stock Item ID])",
            "isDataTypeInferred": true,
            "lineageTag": "44da144f-cde1-4c96-b3f3-820d5dfbc106",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Products",
            "levels": [
              {
                "name": "Category",
                "column": "Category",
                "lineageTag": "bea50457-1bbd-4a2f-a224-bd5bcaf89492",
                "ordinal": 0
              },
              {
                "name": "Stock Item",
                "column": "Stock Item",
                "lineageTag": "06e9eb4d-7e52-4b78-84be-7be5b9a82e99",
                "ordinal": 1
              }
            ],
            "lineageTag": "741d70e0-6109-49cf-b841-232806020c59"
          }
        ],
        "lineageTag": "2e93f205-4e29-44ae-b3d6-23bf0caba8d2",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    #\"Dimension_Stock Item\" = Source{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Dimension_Stock Item\",1),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Top Rows\",{\"Stock Item Key\", \"WWI Stock Item ID\", \"Stock Item\", \"Color\", \"Unit Price\", \"Recommended Retail Price\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Other Columns\", {\"WWI Stock Item ID\"}, DimCategory, {\"WWI Stock Item ID\"}, \"Category dictionary\", JoinKind.LeftOuter),",
                "    #\"Expanded Category dictionary\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Category dictionary\", {\"Category\"}, {\"Category dictionary.Category\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Category dictionary\",{{\"Category dictionary.Category\", \"Category\"}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns\", {\"Color\"}, #\"Color Formats\", {\"Color\"}, \"Color Formats\", JoinKind.LeftOuter),",
                "    #\"Expanded Color Formats\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Color Formats\", {\"Background Color Format\", \"Font Color Format\"}, {\"Color Formats.Background Color Format\", \"Color Formats.Font Color Format\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Color Formats\",{{\"Color Formats.Background Color Format\", \"Background Color Format\"}, {\"Color Formats.Font Color Format\", \"Font Color Format\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactSale",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Sale Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50d8bfea-681a-4227-ae37-4a403798a9de",
            "sourceColumn": "Sale Key",
            "summarizeBy": "count"
          },
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f51959ac-40ff-4592-8efc-38e53b351c6d",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2076b564-c836-4d40-876e-36bf39d4c78e",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a021e608-0580-4f34-9528-832fa0153dd6",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "75651072-eee6-4625-8364-6a083fc3428e",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "94e80c8b-e271-4fa5-a5e9-ca8f133a4bff",
            "sourceColumn": "Salesperson Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cace9599-9aa1-442f-af2c-f7bab27b0f58",
            "sourceColumn": "WWI Invoice ID",
            "summarizeBy": "count"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "711cce3a-f067-414f-bac9-8bd2ed4e9ff1",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "934abd8b-d250-49be-87a7-4a5ac7aee302",
            "sourceColumn": "Unit Price",
            "summarizeBy": "average"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6ac89db-4f9b-4146-88d5-e1a9f8deb217",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Excluding Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09a19880-5f0b-495f-8b35-85b5fb80e972",
            "sourceColumn": "Total Excluding Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dc4304d4-6b95-42e2-a802-c7a2b5589a17",
            "sourceColumn": "Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2686f83-ed4d-49c4-b23f-b5a1e195c750",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Including Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": "Standard Tax",
            "lineageTag": "97730397-2847-47bb-9e33-e4d84e381b25",
            "sourceColumn": "Total Including Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Dry Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f63d2e0a-5754-4e7f-af78-91efc0e8b9d7",
            "sourceColumn": "Total Dry Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Chiller Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa7784dd-b8fa-41bb-b94c-86cb8d813d27",
            "sourceColumn": "Total Chiller Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit Case",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1523225-9680-4b5c-9b6b-12f77b81154a",
            "sourceColumn": "Profit Case",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f92a489-0121-4dd1-8326-e22f27f9570e",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b880c9e0-f114-4068-af65-2160db3496c6",
        "measures": [
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('FactSale'[Total Excluding Tax]) - SUM('FactSale'[Profit])"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalSubtraction",
                  "version": 0
                }
              }
            ],
            "lineageTag": "058dece8-16a5-43e1-8461-1dab6b747632"
          },
          {
            "name": "Profit margin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE(SUM('FactSale'[Profit]), SUM('FactSale'[Total Excluding Tax]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalDivision",
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8b505dff-93de-43d7-922d-861bef183074"
          }
        ],
        "partitions": [
          {
            "name": "FactSale",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"henio\\sqlexpress\", \"WideWorldImportersDW\"),",
                "    Fact_Sale = Source{[Schema=\"Fact\",Item=\"Sale\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Fact_Sale,{\"Sale Key\", \"City Key\", \"Customer Key\", \"Stock Item Key\", \"Invoice Date Key\", \"Delivery Date Key\", \"Salesperson Key\", \"WWI Invoice ID\", \"Quantity\", \"Unit Price\", \"Tax Rate\", \"Total Excluding Tax\", \"Tax Amount\", \"Profit\", \"Total Including Tax\", \"Total Dry Items\", \"Total Chiller Items\", \"Dimension.City\", \"Dimension.Customer(Bill To Customer Key)\", \"Dimension.Customer(Customer Key)\", \"Dimension.Date(Delivery Date Key)\", \"Dimension.Date(Invoice Date Key)\", \"Dimension.Employee\", \"Dimension.Stock Item\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Other Columns\", \"Profit case\", each if [Profit] >= 0 then \"Positive\" else \"Negative\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Conditional Column\", each true),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Delivery Date Key\", \"Delivery Date\"}, {\"Invoice Date Key\", \"Invoice Date\"}, {\"Profit case\", \"Profit Case\"}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each true)",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimSalespersonTarget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12758525-bd8f-4d98-95dd-4514a3b0aa97",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c15ecbaf-115a-45a5-be4f-ac9bb034548b",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e4ea880-4ac3-4d9d-8d62-b9e2fb94ac1e",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bce3d4db-f474-4ac0-95f0-7c56fbf5928d",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1f900e5a-5d1e-4132-b213-e66b08f837ce",
            "sourceColumn": "TargetMonth",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cfade8f2-0b4d-44f0-8cc9-98821e91661c",
        "partitions": [
          {
            "name": "DimSalespersonTarget",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\snosek\\Documents\\studia\\BI\\Dodatkowe dane\\SalespersonTargets.csv\"),[Delimiter=\";\", Columns=14, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"EmployeeID\", Int64.Type}, {\"M01\", Int64.Type}, {\"M02\", Int64.Type}, {\"M03\", Int64.Type}, {\"M04\", Int64.Type}, {\"M05\", Int64.Type}, {\"M06\", Int64.Type}, {\"M07\", Int64.Type}, {\"M08\", Int64.Type}, {\"M09\", Int64.Type}, {\"M10\", Int64.Type}, {\"M11\", Int64.Type}, {\"M12\", Int64.Type}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"EmployeeID\", \"Year\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"MonthNumber\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"M\",\"\",Replacer.ReplaceText,{\"MonthNumber\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"MonthNumber\", Int64.Type}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type1\", \"Merged\", each Text.Combine({Text.From([MonthNumber], \"pl-PL\"), \"-\", Text.From([Year], \"pl-PL\")}), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Merged Column\",{{\"Merged\", \"TargetMonth\"}}),",
                "    #\"Multiplied Column\" = Table.TransformColumns(#\"Renamed Columns1\", {{\"Value\", each _ * 1000, type number}}),",
                "    #\"Duplicated Column\" = Table.AddColumn(#\"Multiplied Column\", \"TargetMonth - Copy\", each [TargetMonth], type text),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"TargetMonth\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type2\",{\"TargetMonth - Copy\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee_csv",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f68fc01d-4e75-429c-9e9b-1e119ea3f8de",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "016711ba-a89c-4ee0-b4a4-810f4a5d0728",
            "sourceColumn": "Employee",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f0e8bd6-34fa-4488-8d49-d735df05e859",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19317de7-f062-450b-9f22-f5d98473e3af",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc8c4f3f-a357-485b-bea8-b1b0850150b3",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "704c1056-32e9-473d-a66a-ea83c88632e7",
        "partitions": [
          {
            "name": "Employee_csv",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\snosek\\Documents\\studia\\BI\\Dodatkowe dane\\Employee_csv.csv\"),[Delimiter=\";\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"WWI Employee ID\", Int64.Type}, {\"Employee\", type text}, {\"JobTitle\", type text}, {\"BusinessUnit\", type text}, {\"Age\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25694fc6-a243-4b11-9794-3682e51a4d95",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2a02823a-01bb-421e-aa25-59a00131d10e",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "133a19f4-b2c9-4895-a91e-4a364d8c8df5",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bc43cec4-fb2a-4ea7-9581-7f13ca6071be",
        "partitions": [
          {
            "name": "DimCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\snosek\\Documents\\studia\\BI\\Dodatkowe dane\\Category_dictionary.xlsx\"), null, true),",
                "    Arkusz1_Sheet = Source{[Item=\"Arkusz1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Arkusz1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"WWI Stock Item ID\", Int64.Type}, {\"Description\", type text}, {\"Category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8dc69fb043244ad1bac33c2ee454ddfa"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d659ef24-dde1-4bfd-b143-7d5ea94cc5d2",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "21a1d063-2d37-4918-b3b1-250505c7769a",
        "measures": [
          {
            "name": "Total Net Sales",
            "expression": "SUM(FactSale[Total Excluding Tax])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "ec9f36ad-5506-4d70-9637-1266a1d3a1f2"
          },
          {
            "name": "Average Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "AVERAGE(FactSale[Unit Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "38f4d996-0bf3-4bf3-94b8-62794538e89b"
          },
          {
            "name": "Total Profit",
            "expression": "SUM(FactSale[Profit])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "ba7e2998-afbc-48d4-981d-d4f547a98955"
          },
          {
            "name": "Profit_Margin",
            "expression": "DIVIDE([Total Profit], [Total Net Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c2a3ba66-cc6a-4da6-b3b8-2a70bba26568"
          },
          {
            "name": "Max Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MAX(FactSale[Unit Price])",
            "lineageTag": "372367a2-79c3-4b42-823a-48599ac24fe6"
          },
          {
            "name": "Min Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MIN(FactSale[Unit Price])",
            "lineageTag": "e21c5b9f-2df3-4269-be54-cb0df5b5ae3b"
          },
          {
            "name": "Median Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MEDIAN(FactSale[Unit Price])",
            "lineageTag": "3598f270-5a84-425d-bc9a-0a3692f00927"
          },
          {
            "name": "Sales 2014",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales],'DimDate'[Calendar Year]=2014)",
            "lineageTag": "c25033bf-3518-4f11-8849-f12bf0aac02b"
          },
          {
            "name": "Filter_Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales], FILTER(FactSale, FactSale[Total Excluding Tax]>5000))",
            "lineageTag": "bd9518fc-c673-4e48-aa6d-ae184c2efa36"
          },
          {
            "name": "Sales PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Net Sales], FILTER(DimProduct, DimProduct[Category]= \"Packaging Materials\"))",
            "lineageTag": "6b2b6170-3a80-4d86-a291-695b182bd451"
          },
          {
            "name": "YTD Total Net Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": "TOTALYTD([Total Net Sales], 'DimDate'[Date])",
            "lineageTag": "32cbf340-5248-440f-9ebf-90966ffa5709"
          },
          {
            "name": "YTD-1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": "CALCULATE([YTD Total Net Sales], SAMEPERIODLASTYEAR(DimDate[Date]))",
            "lineageTag": "eb1e7e0a-22b5-4ca3-a161-d4fb114d6edf"
          },
          {
            "name": "YTD vs YTD-1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": [
              "IF(",
              "    [YTD-1 Total Sales] = 0,",
              "    BLANK(), ",
              "    ([YTD Total Net Sales] - [YTD-1 Total Sales]) ",
              ")"
            ],
            "lineageTag": "830b4d10-7c66-47e4-b25f-89ea7d972952"
          },
          {
            "name": "YTD vs YTD-1 Total Sales percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD",
            "expression": [
              "IF(",
              "    [YTD-1 Total Sales] = 0,",
              "    BLANK(), ",
              "    ([YTD Total Net Sales] - [YTD-1 Total Sales]) / [YTD-1 Total Sales]",
              ")"
            ],
            "lineageTag": "f1a08c38-3b9c-4219-aaa5-0aa247d72ed8"
          },
          {
            "name": "Total Sales Year Ago Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([Total Net Sales], PARALLELPERIOD('DimDate'[Date],",
              "-12, MONTH ))"
            ],
            "lineageTag": "6a1c5c12-f6b7-4ccf-9cf8-077ddd6ec0d0"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM(FactSale[Quantity])",
            "formatString": "0",
            "lineageTag": "367f1d6d-c371-48ac-a6a7-6734e124fd16"
          },
          {
            "name": "YTD Total Quantity",
            "expression": "TOTALYTD([Total Quantity], 'DimDate'[Date])",
            "formatString": "0",
            "lineageTag": "4e123059-3b1b-4a97-ba3e-91e02ad562ac"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity",
            "expression": [
              "IF(",
              "    [YTD-1 Total Quantity] = 0,",
              "    BLANK(), ",
              "    ([YTD Total Quantity] - [YTD-1 Total Quantity])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c9c7635f-4f33-4733-b8a0-888e83973933"
          },
          {
            "name": "YTD-1 Total Quantity",
            "expression": "CALCULATE([YTD Total Quantity], SAMEPERIODLASTYEAR(DimDate[Date]))",
            "formatString": "0",
            "lineageTag": "2bc86984-02d8-45aa-9d77-52431770e143"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity %",
            "expression": [
              "",
              "IF(",
              "    [YTD-1 Total Quantity] = 0,",
              "    BLANK(), ",
              "    ([YTD Total Quantity] - [YTD-1 Total Quantity]) / [YTD-1 Total Quantity]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b5222b07-1e8b-48a4-ac2c-5ef7ae514c7a"
          },
          {
            "name": "Sales % Country",
            "expression": "[Total Net Sales]/[Total Net Sales Country]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "97afaef8-acf0-429a-bb6e-2d931311cd64"
          },
          {
            "name": "Sales % Province",
            "expression": [
              "",
              "    DIVIDE(",
              "        SUM('FactSale'[Total Excluding Tax]),",
              "        CALCULATE(",
              "            SUM('FactSale'[Total Excluding Tax]), ",
              "            REMOVEFILTERS('DimCity'[City]),",
              "            ALLEXCEPT('DimCity', 'DimCity'[State Province])",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3a5d0c54-3269-4029-9020-e72563ed0538"
          },
          {
            "name": "Quantity % Province",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        SUM('FactSale'[Quantity]),",
              "        CALCULATE(",
              "            SUM('FactSale'[Quantity]), ",
              "            REMOVEFILTERS('DimCity'[City]),",
              "            ALLEXCEPT('DimCity', 'DimCity'[State Province])",
              "        )",
              "    )"
            ],
            "lineageTag": "2f4a5300-1147-49cc-8f98-95b513fe4820"
          },
          {
            "name": "Quantity % Country",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    DIVIDE(",
              "        SUM('FactSale'[Quantity]),",
              "        CALCULATE(",
              "            SUM('FactSale'[Quantity]), ",
              "            REMOVEFILTERS('DimCity'[City]),",
              "            ALL('DimCity'[City], 'DimCity'[State Province])",
              "        )",
              "    )"
            ],
            "lineageTag": "740067ba-ad3d-4d6f-9120-bc3ce5ff5daa"
          },
          {
            "name": "Categorize",
            "expression": "SWITCH(TRUE(), [Total Net Sales] > 10000, \"High\", [Total Net Sales] > 5000, \"Medium\", \"Low\")",
            "lineageTag": "0225d7e4-f27d-4469-ae34-2e621964a75f"
          },
          {
            "name": "Total orders",
            "expression": "DISTINCTCOUNT(FactSale[WWI Invoice ID])",
            "formatString": "0",
            "lineageTag": "0bcb765c-d703-41bd-aa16-e58dda545aa9"
          },
          {
            "name": "Target YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "TOTALYTD([Target], 'DimDate'[Date])",
              "  ",
              ""
            ],
            "lineageTag": "68bebb8b-7eb9-4f84-9d66-9c4c8785c8dd"
          },
          {
            "name": "Total Excluding Tax minus Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM('FactSale'[Total Excluding Tax]) - SUM('FactSale'[Profit])"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalSubtraction",
                  "version": 0
                }
              }
            ],
            "lineageTag": "209842f5-05c7-4000-a7b8-5a0b525a6d85"
          },
          {
            "name": "Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(DimSalespersonTarget[Value])",
            "lineageTag": "735a2928-4607-479c-b24e-9dcdcad39b84"
          },
          {
            "name": "Sales_Target_diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[YTD Total Net Sales] - [Target YTD]"
            ],
            "lineageTag": "782bca0a-fba2-40a7-87d2-d455f006728d"
          },
          {
            "name": "Sales_Target_diff_%",
            "expression": [
              "",
              "DIVIDE(",
              "    [Sales_Target_diff],",
              "    [YTD Total Net Sales],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "adb7f7e9-32e9-4889-a04e-159ba7085af5"
          },
          {
            "name": "Total Excluding Tax",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM('FactSale'[Total Excluding Tax])"
            ],
            "lineageTag": "70744091-ec73-413d-9ecc-730961b4833e"
          },
          {
            "name": "Total Including Tax",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(FactSale[Total Including Tax])",
            "lineageTag": "b5f1b8a9-da72-4dd9-93ea-434cc8a9f0de"
          },
          {
            "name": "Total Quantity Year Ago Month",
            "expression": [
              "CALCULATE([Total Quantity], PARALLELPERIOD('DimDate'[Date],",
              "-12, MONTH ))"
            ],
            "formatString": "0",
            "lineageTag": "fa3892cf-cc53-4d63-bfb4-a8a14391c583"
          },
          {
            "name": "Total Net Sales Teritory",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('FactSale'[Total Excluding Tax]), REMOVEFILTERS('DimCity'[City]))",
            "lineageTag": "bf3dcf9b-82b3-48b7-952c-0f3337f1c422"
          },
          {
            "name": "Sales_%_Territory",
            "expression": "[Total Net Sales]/[Total Net Sales Teritory]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f7b43ce9-1dd9-4fa9-a959-bba0c2b3c6d8"
          },
          {
            "name": "Total Net Sales Country",
            "expression": "CALCULATE(SUM('FactSale'[Total Excluding Tax]), REMOVEFILTERS('DimCity'[Sales Territory], 'DimCity'[City]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "022a0713-6583-47ca-899e-e407d2b50c2c"
          },
          {
            "name": "Sales_realization_YTD_%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[YTD Total Net Sales]/[Target YTD]",
            "lineageTag": "5ab1404f-569e-4707-95e9-00872dae855b"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(FactSale[Total Including Tax]), FactSale[Profit case]=\"Positive\")",
            "lineageTag": "7621ae67-c1d5-4725-834e-809467f00694"
          },
          {
            "name": "Average Order Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Sales] / COUNT(FactSale[WWI Invoice ID])",
            "lineageTag": "e0ee0d18-8d2f-404e-a3a7-143513e4c97d"
          },
          {
            "name": "Potential",
            "expression": "IF([Average Order Value] > 1000, \"High\", \"Low\")",
            "lineageTag": "7c4dbc5a-f13a-4555-b28b-fb9f31ce28a2"
          },
          {
            "name": "Growth Potential",
            "expression": "IF(COUNT(FactSale[WWI Invoice ID]) < 350 && [Average Order Value] > 900, \"Potential for Growth\", \"Stable\")",
            "lineageTag": "60cc6d5c-838d-4028-8fcc-aa2a1053fc4b"
          },
          {
            "name": "Max Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    MAXX(",
              "        ALL(DimSalesperson[Salesperson]),",
              "        CALCULATE(SUM(FactSale[Total Including Tax])-1, FactSale[Profit Case]=\"Positive\"))"
            ],
            "lineageTag": "a462bfd4-38e4-4048-8184-79e64aa14572"
          },
          {
            "name": "Is Best Salesperson",
            "expression": [
              "",
              "IF([Total Sales] = [Max Total Sales], 1, 0)"
            ],
            "formatString": "0",
            "lineageTag": "ad46636a-e418-442b-a860-6bf7e2fd7089"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dimension Stock Item",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ebfee24-a1b1-4331-a189-8fa3bc201509",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8566d96f-e8f4-4df9-beaa-7b3e5957348f",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f066b03-f6ec-4540-a5a1-0c20ef0e5399",
            "sourceColumn": "Stock Item",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c79ab79-9a38-46b1-955f-cd526689ca5d",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Selling Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e47d6608-f626-4741-b5c2-7699999c4236",
            "sourceColumn": "Selling Package",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1907d0bf-b9f8-49e8-a71e-83f935291bcd",
            "sourceColumn": "Buying Package",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "071bec1b-b3d7-4970-96c5-a095cc49315c",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "823ccf80-d5b4-4816-bf64-2366201d8c41",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Time Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd3a2a59-0cd1-49bc-94c4-f1e590faaf76",
            "sourceColumn": "Lead Time Days",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity Per Outer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8518ba9-3f87-4331-a56e-b9dae18c4103",
            "sourceColumn": "Quantity Per Outer",
            "summarizeBy": "none"
          },
          {
            "name": "Is Chiller Stock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c6cf2404-163c-45c2-84a5-aa43c9e6309d",
            "sourceColumn": "Is Chiller Stock",
            "summarizeBy": "none"
          },
          {
            "name": "Barcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d53ca8c-07c4-49f5-ab30-3f5db8554416",
            "sourceColumn": "Barcode",
            "summarizeBy": "none"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad13ae7f-3e9d-4824-a31b-41f556fe9e24",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0354d7a3-1258-4221-93e6-dd2017349cb1",
            "sourceColumn": "Unit Price",
            "summarizeBy": "none"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e9ada5f-e788-4bf0-bd53-20670d520c54",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "none"
          },
          {
            "name": "Typical Weight Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e67b9279-ee4a-4d97-8272-047203d8b778",
            "sourceColumn": "Typical Weight Per Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "abd691e8-737d-4c29-8707-233be40d6db9",
            "sourceColumn": "Valid From",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2d61e4d9-805d-4b51-9bf9-8cf5411ec604",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79365f99-28fb-49fc-86ce-afe4ca88dd3f",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "792aafbf-4430-4a30-bd53-aa37dc109f61",
        "partitions": [
          {
            "name": "Dimension Stock Item",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"henio\\sqlexpress\"),",
                "    WideWorldImportersDW = Source{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    #\"Dimension_Stock Item\" = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data]",
                "in",
                "    #\"Dimension_Stock Item\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}